#!/bin/bash
#PBS -P mr51
#PBS -q normal
#PBS -l storage=gdata/xc0+gdata/u39+gdata/ub8+scratch/mr51
#PBS -l ncpus=1
#PBS -l mem=20GB
#PBS -l walltime=48:00:00
#PBS -l jobfs=100GB

module load cdo


/g/data/xc0/software/conda-envs/rs3/bin/python /g/data/xc0/user/scortechini/github/fire-data-processing/deciles/zonalstats_zonal_stats_absolute.py -mosfolder /g/data/ub8/au/FMC/mosaics -vegmaskfolder /g/data/ub8/au/FMC/intermediary_files/vegetation_mask -areafolder /g/data/ub8/au/FMC/intermediary_files/areal_classifications -area ${area} -var ${var} -ystart ${year} -yend ${year} -outfolder /scratch/mr51/gs3146/stats/${year} -tmpfolder $PBS_JOBFS
